#%RAML 1.0
title: My Api
baseUri: http://httpbin.org/


/post:
  post:
    body:
      application/json:
        type: object
        properties:
          aString: string
          aBoolean: boolean
          aNumber: number
