#%RAML 1.0
title: GitHub API
version: v3
baseUri: https://api.github.com

/{userId}:
 description: A specific user
 uriParameters:
   userId:
     description: The id of the user
     type: integer
 get: